# -*- coding: utf-8 -*-
"""temperature.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1984yCGm_m6rB-3y1rv-Zpd1UrD9EPUXZ
"""

import requests
from bs4 import BeautifulSoup

search="Weather in delhi"
url = f"https://www.google.com/search?&q={search}"

r = requests.get(url)

s = BeautifulSoup(r.text,"html.parser")
update = s.find("div", class_="BNeawe").text
print(update)
